server:
  port: 8761

spring:
  application:
    name: service-eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka-pacs:8761/eureka/
