server:
  port: 8761
  servlet:
    context-path: /service-discovery

spring:
  application:
    name: eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/service-discovery/eureka/
