server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
